In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Environment is ready!")

Environment is ready!

In [19]:
df = pd.read_csv("../data/raw/samsung_phones.csv")

In [20]:
df.head()

,model_name,series,launch_year,price_inr,ram_gb,storage_gb,processor_score,main_camera_mp,ultrawide_mp,telephoto_mp,front_camera_mp,ois,battery_mah,charging_w,refresh_rate_hz,screen_size_inch,weight_g,ai_features,waterproof,target_segment
0,Galaxy A06,A,2025,10999,4,64,3.5,50,2,0,8,No,5000,25,60,6.7,189,No,No,budget
1,Galaxy A15 5G,A,2024,17999,6,128,5.0,50,2,0,13,No,5000,25,90,6.5,200,No,No,budget
2,Galaxy A16 5G,A,2025,19999,8,128,5.5,48,8,0,13,No,5000,25,90,6.7,198,Basic AI,No,budget
3,Galaxy A25 5G,A,2024,24999,8,128,6.2,48,8,0,13,No,5000,25,120,6.5,197,Basic AI,No,budget
4,Galaxy A26 5G,A,2025,27999,8,256,6.5,64,8,0,13,Yes,5000,25,120,6.7,197,Basic AI,Yes,photography

In [21]:
df.describe()

,launch_year,price_inr,ram_gb,storage_gb,processor_score,main_camera_mp,ultrawide_mp,telephoto_mp,front_camera_mp,battery_mah,charging_w,refresh_rate_hz,screen_size_inch,weight_g
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,2024.566667,56132.333333,9.200000,258.133333,7.803333,71.666667,9.600000,7.133333,17.433333,4918.333333,32.000000,112.000000,6.650000,204.800000
std,0.504007,42266.586896,2.905405,130.711510,1.796641,47.398773,3.499754,12.408933,9.000702,662.477499,10.221681,17.498768,0.234521,21.920546
min,2024.000000,10999.000000,4.000000,64.000000,3.500000,32.000000,2.000000,0.000000,8.000000,3900.000000,15.000000,60.000000,6.200000,163.000000
25%,2024.000000,27249.000000,8.000000,128.000000,6.625000,50.000000,8.000000,0.000000,12.000000,4425.000000,25.000000,120.000000,6.600000,189.250000
50%,2025.000000,36999.000000,8.000000,256.000000,7.800000,50.000000,12.000000,5.000000,13.000000,5000.000000,25.000000,120.000000,6.700000,207.000000
75%,2025.000000,82499.000000,12.000000,256.000000,9.650000,64.000000,12.000000,10.000000,27.250000,5000.000000,45.000000,120.000000,6.700000,219.500000
max,2025.000000,169999.000000,16.000000,512.000000,10.000000,200.000000,12.000000,50.000000,32.000000,6500.000000,45.000000,120.000000,7.600000,240.000000

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   model_name        30 non-null     str
 1   series            30 non-null     str
 2   launch_year       30 non-null     int64
 3   price_inr         30 non-null     int64
 4   ram_gb            30 non-null     int64
 5   storage_gb        30 non-null     int64
 6   processor_score   30 non-null     float64
 7   main_camera_mp    30 non-null     int64
 8   ultrawide_mp      30 non-null     int64
 9   telephoto_mp      30 non-null     int64
 10  front_camera_mp   30 non-null     int64
 11  ois               30 non-null     str
 12  battery_mah       30 non-null     int64
 13  charging_w        30 non-null     int64
 14  refresh_rate_hz   30 non-null     int64
 15  screen_size_inch  30 non-null     float64
 16  weight_g          30 non-null     int64
 17  ai_features       30 non-null     str
 18  waterproof        30 non-null     str
 19  target_segment    30 non-null     str
dtypes: float64(2), int64(12), str(6)
memory usage: 4.8 KB

In [23]:
df.shape

(30, 20)

In [24]:
df.columns

Index(['model_name', 'series', 'launch_year', 'price_inr', 'ram_gb',
       'storage_gb', 'processor_score', 'main_camera_mp', 'ultrawide_mp',
       'telephoto_mp', 'front_camera_mp', 'ois', 'battery_mah', 'charging_w',
       'refresh_rate_hz', 'screen_size_inch', 'weight_g', 'ai_features',
       'waterproof', 'target_segment'],
      dtype='str')

In [25]:
df.sample(5, random_state=42)

,model_name,series,launch_year,price_inr,ram_gb,storage_gb,processor_score,main_camera_mp,ultrawide_mp,telephoto_mp,front_camera_mp,ois,battery_mah,charging_w,refresh_rate_hz,screen_size_inch,weight_g,ai_features,waterproof,target_segment
27,Galaxy XCover8 Pro,XCover,2025,49999,8,256,7.8,50,12,0,32,Yes,4350,25,120,6.6,235,Galaxy AI,Yes,business
15,Galaxy S24 FE,S,2025,59999,8,256,9.2,50,12,10,12,Yes,4700,25,120,6.7,213,Galaxy AI,Yes,photography
23,Galaxy S25 Edge,S,2025,114999,12,512,9.9,200,12,10,12,Yes,3900,45,120,6.7,163,Galaxy AI,Yes,photography
17,Galaxy S24+,S,2024,94999,12,256,9.7,50,12,10,12,Yes,4900,45,120,6.7,197,Galaxy AI,Yes,business
8,Galaxy M15 5G,M,2024,15999,6,128,5.2,48,2,0,13,No,6000,25,90,6.5,217,No,No,budget

In [26]:
import os
print(os.getcwd())

c:\Users\la1886\Desktop\Samsung-Mobile-Recommendation-System\notebooks

In [27]:

df.isnull().sum()

model_name          0
series              0
launch_year         0
price_inr           0
ram_gb              0
storage_gb          0
processor_score     0
main_camera_mp      0
ultrawide_mp        0
telephoto_mp        0
front_camera_mp     0
ois                 0
battery_mah         0
charging_w          0
refresh_rate_hz     0
screen_size_inch    0
weight_g            0
ai_features         0
waterproof          0
target_segment      0
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
categorical_cols = ["series", "ai_features", "waterproof", "target_segment"]

for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].value_counts)

series
<bound method IndexOpsMixin.value_counts of 0          A
1          A
2          A
3          A
4          A
5          A
6          A
7          A
8          M
9          M
10         M
11         F
12         F
13         F
14         S
15         S
16         S
17         S
18         S
19         Z
20         Z
21         S
22         S
23         S
24         S
25    XCover
26    XCover
27    XCover
28         M
29         F
Name: series, dtype: str>

ai_features
<bound method IndexOpsMixin.value_counts of 0            No
1            No
2      Basic AI
3      Basic AI
4      Basic AI
5     Galaxy AI
6     Galaxy AI
7     Galaxy AI
8            No
9      Basic AI
10    Galaxy AI
11           No
12     Basic AI
13    Galaxy AI
14    Galaxy AI
15    Galaxy AI
16    Galaxy AI
17    Galaxy AI
18    Galaxy AI
19    Galaxy AI
20    Galaxy AI
21    Galaxy AI
22    Galaxy AI
23    Galaxy AI
24    Galaxy AI
25     Basic AI
26     Basic AI
27    Galaxy AI
28    Galaxy AI
29    Galaxy AI
Name: ai_features, dtype: str>

waterproof
<bound method IndexOpsMixin.value_counts of 0      No
1      No
2      No
3      No
4     Yes
5     Yes
6     Yes
7     Yes
8      No
9      No
10    Yes
11     No
12     No
13    Yes
14    Yes
15    Yes
16    Yes
17    Yes
18    Yes
19    Yes
20    Yes
21    Yes
22    Yes
23    Yes
24    Yes
25    Yes
26    Yes
27    Yes
28     No
29    Yes
Name: waterproof, dtype: str>

target_segment
<bound method IndexOpsMixin.value_counts of 0          budget
1          budget
2          budget
3          budget
4     photography
5     photography
6          gaming
7        business
8          budget
9          gaming
10         gaming
11         budget
12         gaming
13    photography
14         gaming
15    photography
16       business
17       business
18    photography
19    photography
20       business
21       business
22         gaming
23    photography
24    photography
25       business
26       business
27       business
28         gaming
29    photography
Name: target_segment, dtype: str>

In [ ]:
numeric_cols = [
    "price_inr",
    "ram_gb",
    "storage_gb",
    "processor_score",
    "main_camera_mp",
    "ultrawide_mp",
    "telephoto_mp",
    "front_camera_mp",
    "battery_mah"
]

df[numeric_cols].describe()

KeyError: "['camera_mp'] not in index"

In [ ]:
(df["price_inr"] <= 0).sum()

np.int64(0)

In [ ]:
(df["ram_gb"] <= 0).sum()
(df["battery_mah"] <= 0).sum()

np.int64(0)

In [ ]:
df.to_csv("../data/processed/cleaned_samsung_phones.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!